### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mighani** [JackMGrundy/tech-skills-scraper-and-visualizer#1]
Hi Jack,

does a specific license apply to your repo? Apache, BSD, CC or anything?
Can the code be used freely for whatever purpose?

Thanks

**Comment by JackMGrundy** [comment]
Hi Mighani,
Thank you for pointing this out. I just added the standard MIT license. If you need any further clarification, please let me know, and I'll get back to you ASAP.

Best,
Jack
